### ISSUE TITLE
Can not work?

### ISSUE THREAD

**Issue by wsycysdrhpa** [zcold/pycnnum#2]
hi, my system is python27, when i run the example, it is say:
AttributeError: 'ChineseNumberUnit' object has no attribute 'value'.
How could i do for that?

**Comment by zcold** [comment]
Sorry to hear this.
I am using python 3. 
Can you paste your code and full trace log?

**Comment by wsycysdrhpa** [comment]
Thanks for reply.
I have tried under python2 and python3. but did not work neither python2 and python3.
The detail as follows. Thanks!

Code：
from pycnnum import cn2num, num2cn
print('num:', cn2num('十'))
print('num:', cn2num('一亿六点三'))
c = num2cn(33212222222, numbering_type = 'high', alt_two = True, big = True, traditional= True)
print(c)


Python2 bug：
[haipeng@lv-voice-rt-01 python_test]$ python2 test.py 
('num:', 1000)
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    print('num:', cn2num('一亿六点三'))
  File "/data/nfs_ssd/ruanhp1/anaconda2/lib/python2.7/site-packages/pycnnum.py", line 229, in cn2num
    dec_str = ''.join([str(d.value) for d in dec_part])
AttributeError: 'ChineseNumberUnit' object has no attribute 'value'


python3 bug:
[haipeng@lv-voice-rt-01 python_test]$ python3 test.py 
num: 10
num: 160000000.3
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    c = num2cn(33212222222, numbering_type = 'high', alt_two = True, big = True, traditional= True)
TypeError: num2cn() got an unexpected keyword argument 'numbering_type'




------------------ 原始邮件 ------------------
发件人: "Shuo Li"<notifications@github.com>;
发送时间: 2018年2月26日(星期一) 凌晨3:06
收件人: "zcold/pycnnum"<pycnnum@noreply.github.com>;
抄送: "天鹏元帅"<342369984@qq.com>; "Author"<author@noreply.github.com>;
主题: Re: [zcold/pycnnum] Can not work? (#2)

Sorry to hear this.
I am using python 3.
Can you paste your code and full trace log?
